spring.application.name=treckingApp
spring.datasource.url=jdbc:postgresql://localhost:5432/app
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt_secret = f3a9c1d7e8b4f2a6c9d1e7f3a8b5c2d6e9f1a4c7b8d3e6f1a9c2d5e8f7b1a4c